"""empty message

Revision ID: 9ae1d8d2023d
Revises: b3e9b52b596a
Create Date: 2019-06-24 16:37:45.406101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae1d8d2023d'
down_revision = 'b3e9b52b596a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('delivery_destination', sa.String(length=255), nullable=True))
    op.add_column('parcels', sa.Column('parcel_name', sa.String(length=255), nullable=True))
    op.add_column('parcels', sa.Column('parcel_number', sa.Integer(), nullable=True))
    op.add_column('parcels', sa.Column('pickup_destination', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'pickup_destination')
    op.drop_column('parcels', 'parcel_number')
    op.drop_column('parcels', 'parcel_name')
    op.drop_column('parcels', 'delivery_destination')
    # ### end Alembic commands ###
